import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Denuncie Chamas - Login",
  description: "Generated by create next app",
};

export default function PrivateLayout({ children }) {
  return (
    <body style={{ backgroundColor: "#e2cec4" }}>
      <main>{children}</main>
    </body>
  );
}