import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Denuncie Chamas - Reports",
  description: "Generated by create next app",
};

export default function ReportLayout({ children }) {
  return (
    <body style={{ backgroundColor: "#ebedf0" }}>
      <Header/>
      <main>{children}</main>
    </body>
  );
}